"""PreToolUse hook: refuse hand-edits to generated documentation views.

Two directories hold one hand-written source and views generated from it:

- ``docs/design/domain-model/``: source ``domain-model.dbml``,
  generated by the ``domain-model`` skill;
- ``docs/product/features/``: source ``features.yaml``, generated by
  the ``feature-catalog`` skill.

A hand-edit to a generated file would be overwritten and makes ``make check``
fail, so the hook denies Write/Edit on those files and tells Claude to edit the
source and regenerate.
"""

import json
import os
import sys
from pathlib import Path

# Generated directory -> (its single hand-written source, the skill that
# regenerates the rest).
GENERATED_DIRS = {
    Path("docs/design/domain-model"): (
        Path("docs/design/domain-model/domain-model.dbml"),
        "domain-model",
    ),
    Path("docs/product/features"): (
        Path("docs/product/features/features.yaml"),
        "feature-catalog",
    ),
}


def main() -> None:
    """Print a deny decision when the target is a generated view."""
    payload = json.load(sys.stdin)
    file_path = (payload.get("tool_input") or {}).get("file_path") or ""
    project_dir = Path(os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd") or ".")
    try:
        relative = Path(file_path).resolve().relative_to(project_dir.resolve())
    except ValueError:
        return
    for generated_dir, (source_file, skill) in GENERATED_DIRS.items():
        if relative == source_file or generated_dir not in relative.parents:
            continue
        print(
            json.dumps(
                {
                    "hookSpecificOutput": {
                        "hookEventName": "PreToolUse",
                        "permissionDecision": "deny",
                        "permissionDecisionReason": (
                            f"{relative} is generated. Edit {source_file} instead, "
                            f"then regenerate with the {skill} skill's `generate` "
                            "command."
                        ),
                    }
                }
            )
        )
        return


if __name__ == "__main__":
    main()
