"""PreToolUse hook: refuse hand-edits to the generated domain-model views.

Everything under ``docs/01-requirements/domain-model/`` except
``domain-model.dbml`` is generated by the ``domain-model`` skill's script, so a
hand-edit would be overwritten and makes ``make check`` fail. The hook denies
Write/Edit on those files and tells Claude to edit the DBML and regenerate.
"""

import json
import os
import sys
from pathlib import Path

GENERATED_DIR = Path("docs/01-requirements/domain-model")
SOURCE_FILE = GENERATED_DIR / "domain-model.dbml"


def main() -> None:
    """Print a deny decision when the target is a generated view."""
    payload = json.load(sys.stdin)
    file_path = (payload.get("tool_input") or {}).get("file_path") or ""
    project_dir = Path(os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd") or ".")
    try:
        relative = Path(file_path).resolve().relative_to(project_dir.resolve())
    except ValueError:
        return
    if relative == SOURCE_FILE or GENERATED_DIR not in relative.parents:
        return
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": (
                        f"{relative} is generated. Edit {SOURCE_FILE} instead, then "
                        "regenerate with the domain-model skill's `generate` command."
                    ),
                }
            }
        )
    )


if __name__ == "__main__":
    main()
