"""create vehicle_telemetry hypertable

Revision ID: 70cefd03d3d5
Revises: 90df58f189f6
Create Date: 2026-07-25 02:05:49.151479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70cefd03d3d5'
down_revision: Union[str, None] = '90df58f189f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_telemetry',
    sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_uuid', sa.UUID(), nullable=False),
    sa.Column('telematic_id', sa.UUID(), nullable=False),
    sa.Column('telematic_serial', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('speed', sa.Double(), nullable=True),
    sa.Column('heading', sa.Double(), nullable=True),
    sa.Column('soc', sa.Double(), nullable=False),
    sa.Column('battery_voltage', sa.Double(), nullable=True),
    sa.Column('battery_current', sa.Double(), nullable=True),
    sa.Column('battery_temperature', sa.Double(), nullable=True),
    sa.Column('motor_temperature', sa.Double(), nullable=True),
    sa.Column('odometer', sa.Double(), nullable=True),
    sa.Column('signal_strength', sa.BigInteger(), nullable=True),
    sa.Column('error_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['telematic_id'], ['telematics.telematic_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'recorded_at'),
    sa.UniqueConstraint('telematic_id', 'recorded_at', name='uq_telematic_recorded_at')
    )
    op.create_index(op.f('ix_vehicle_telemetry_message_uuid'), 'vehicle_telemetry', ['message_uuid'], unique=False)
    op.create_index('ix_vehicle_telemetry_vehicle_time', 'vehicle_telemetry', ['vehicle_id', sa.literal_column('recorded_at DESC')], unique=False)
    
    # Convert to TimescaleDB hypertable
    op.execute(
        "SELECT create_hypertable('vehicle_telemetry', 'recorded_at', "
        "chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_telemetry_vehicle_time', table_name='vehicle_telemetry')
    op.drop_index(op.f('ix_vehicle_telemetry_message_uuid'), table_name='vehicle_telemetry')
    op.drop_table('vehicle_telemetry')
    # ### end Alembic commands ###
